version: '3.8'
services:
  recommender_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./schema_init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local