version: '3.8'
services:
  recommender_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${PORT}:5432
    volumes:
      - ./schema_init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local